import type { Metadata } from "next";import { Theme } from "@radix-ui/themes";
import localFont from "next/font/local";
import "@radix-ui/themes/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoCondensed = localFont({
  src: "./fonts/RobotoCondensed.ttf",
  variable: "--font-roboto-condensed",
  weight: "400 700"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoCondensed.variable} `}>
        <Theme appearance="dark">
          {children}
        </Theme>
      </body>
    </html>
  );
}